env: local
http:
  port: 8000
security:
  api_sign:
    app_key: 123456
    app_security: 123456
  jwt:
    key: QQYnRFerJTSEcrfB89fw8prOaObmrch8
data:
  mysql:
    user: root:cYRBsFbTW3SjYNKq@tcp(rm-bp14r05p0kyj81sleso.mysql.rds.aliyuncs.com:3306)/track5music?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 150.158.42.154:6379
    password: "cYRBsFbTW3SjYNKq"
    db: 1
    read_timeout: 0.2s
    write_timeout: 0.2s

log:
  log_level: warn
  encoding: console           # json or console
  log_file_name: "./storage/logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true

aws:
  access_key: AKIASKJKUNBIVEWW2FHK
  secret_key: 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
  bucket_name: track5music
  region: ap-east-1

