// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"backend/internal/handler"
	"backend/internal/repository"
	"backend/internal/server"
	"backend/internal/service"
	"backend/pkg/aws"
	"backend/pkg/helper/sid"
	"backend/pkg/jwt"
	"backend/pkg/log"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewApp(viperViper *viper.Viper, logger *log.Logger) (*server.Server, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	sidSid := sid.NewSid()
	bucketBasics := aws.NewS3(viperViper)
	serviceService := service.NewService(logger, sidSid, jwtJWT, bucketBasics)
	db := repository.NewDB(viperViper)
	client := repository.NewRedis(viperViper)
	repositoryRepository := repository.NewRepository(db, client, logger)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	musicRepository := repository.NewMusicRepository(repositoryRepository)
	musicService := service.NewMusicService(serviceService, musicRepository)
	musicHandler := handler.NewMusicHandler(handlerHandler, musicService)
	engine := server.NewServerHTTP(logger, jwtJWT, userHandler, musicHandler)
	serverServer := server.NewServer(engine)
	return serverServer, func() {
	}, nil
}

// wire.go:

var HandlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewMusicHandler)

var ServiceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewMusicService)

var RepositorySet = wire.NewSet(repository.NewDB, repository.NewRedis, repository.NewRepository, repository.NewUserRepository, repository.NewMusicRepository)
